# Generated by Django 4.0.1 on 2022-01-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetracker',
            name='project',
        ),
        migrations.RemoveField(
            model_name='timetracker',
            name='tags',
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='end_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='start_at',
            field=models.DateTimeField(),
        ),
    ]
